ydlidar_node:
  ros__parameters:
    port: "/dev/ttyS2"
    frame_id: "laser_link"
    ignore_array: ""
    baudrate: 115200
    samp_rate: 4
    fixed_resolution: true
    singleChannel: true
    auto_reconnect: true
    reversion: false
    isToFLidar: false
    angle_max: 180.0
    angle_min: -180.0
    max_range: 8.0
    min_range: 0.1
    frequency: 10.0
