/chassis:
  ros__parameters:
    imu:
      # mode zyz/atk/mpu6050/mpu9250
      module: "atk"
      # IMU端口
      port: "/dev/ttyS8"
      # 波特率
      baudrate: 921600
    remote:
      # 遥控类型 sbus/gamepad/keyboard/socket/sonnyps2
      type: "sbus"
      # 端口
      port: "/dev/ttyS4"
      # 波特率
      baudrate: 100000
      # 1帧数据长度
      data_len: 25
      # 最大量程
      joy_var_max: 1800
      # 最小量程
      joy_var_min: 199
      # 线速度最大值 单位m/s
      max_x_vel: 0.4
      # 角速度最大值 单位rad/s
      max_w_vel: 5.0
      # 最大转向角
      max_angle: 0.758
    driver:
      chip: "Ackerman"
      bts7960_lis: -1
      bts7960_ris": -1
      moto_ena: "moto-ena"
      moto_enb: "moto-enb"
      lidar_pwm:
        chip: 1
        channel: 0
        polarity: true
        period: 30000000
        dutycycle: 15000000
      moto_pwm: 
        chip: 3
        channel: 0
        polarity: true
        period: 40000
        dutycycle: 0
      servo_pwm:
        chip: 4
        channel: 0
        polarity: true
        period: 20000000
        dutycycle: 1500000
      RotaryEncoder:
        - "rotary-encoder"
    car_param:
      LeftWheelRadius: 0.0315
      RightWheelRadius: 0.0315
      TrendLength: 0.15
      WheelBase: 0.1
      Ticks1Roll: 494.5
      MaxXVel: 0.389079
      MaxWVel: 5.18772
      MaxAngle: 0.758
      ZeroAngle: 0.0
      MaxXAcc: 0.5
      MaxWAcc: 0.5
      MaxAngerLimit : 0.785399
      MinAngerLimit : -0.785399
      # K 比例系数
      Proportion: 45.0
      # I 积分系数
      Integration: 3.25
      # D 微分系数
      Differentiation: 0.0
    # 超声波
    srf04: false
    # tof激光测距
    vl53l0x: false
    # 录制数据开关
    record_data: false
    # 视频设备
    video_device:
      # 直播开关
      live_video: false
      dev: "/dev/video1"
      format: "YUV"
      width: 640
      height: 480
      fps: 30
